export const typesConges = [
  "Congé annuel",
  "Congé maladie",
  "Absence exceptionnelle",
  "Congé maternité/paternité",
];

export const mockConges = [
  {
    id: 1,
    employeId: 3,
    employeNom: "Awa Sarr",
    type: "Congé annuel",
    dateDebut: "2026-07-14",
    dateFin: "2026-07-21",
    jours: 6,
    statut: "en_attente",
    motif: "Congés d'été en famille",
  },
  {
    id: 2,
    employeId: 4,
    employeNom: "Ibrahima Ba",
    type: "Congé maladie",
    dateDebut: "2026-07-01",
    dateFin: "2026-07-03",
    jours: 3,
    statut: "validee",
    motif: "Grippe",
  },
  {
    id: 3,
    employeId: 6,
    employeNom: "Cheikh Kanté",
    type: "Congé annuel",
    dateDebut: "2026-08-01",
    dateFin: "2026-08-10",
    jours: 8,
    statut: "en_attente",
    motif: "Vacances",
  },
  {
    id: 4,
    employeId: 10,
    employeNom: "Modou Seck",
    type: "Absence exceptionnelle",
    dateDebut: "2026-06-20",
    dateFin: "2026-06-20",
    jours: 1,
    statut: "refusee",
    motif: "Raison personnelle",
  },
  {
    id: 5,
    employeId: 3,
    employeNom: "Awa Sarr",
    type: "Congé maladie",
    dateDebut: "2026-05-10",
    dateFin: "2026-05-12",
    jours: 2,
    statut: "validee",
    motif: "Consultation médicale",
  },
];
