export const categoriesFormation = [
  "Technique",
  "Management",
  "Soft Skills",
  "Sécurité",
  "Langues",
];

export const mockFormations = [
  {
    id: 1,
    titre: "React avancé & Performance",
    categorie: "Technique",
    formateur: "Awa Sarr",
    dateDebut: "2026-08-10",
    dateFin: "2026-08-12",
    placesTotal: 12,
    statut: "ouverte",
  },
  {
    id: 2,
    titre: "Management d'équipe agile",
    categorie: "Management",
    formateur: "Cabinet externe RH+",
    dateDebut: "2026-08-20",
    dateFin: "2026-08-21",
    placesTotal: 10,
    statut: "ouverte",
  },
  {
    id: 3,
    titre: "Prise de parole en public",
    categorie: "Soft Skills",
    formateur: "Fatou Ndiaye",
    dateDebut: "2026-07-25",
    dateFin: "2026-07-25",
    placesTotal: 15,
    statut: "ouverte",
  },
  {
    id: 4,
    titre: "Sécurité informatique & RGPD",
    categorie: "Sécurité",
    formateur: "Cabinet externe SecureIT",
    dateDebut: "2026-06-05",
    dateFin: "2026-06-06",
    placesTotal: 20,
    statut: "fermee",
  },
  {
    id: 5,
    titre: "Anglais professionnel",
    categorie: "Langues",
    formateur: "Modou Seck",
    dateDebut: "2026-09-01",
    dateFin: "2026-10-15",
    placesTotal: 8,
    statut: "ouverte",
  },
];

export const mockInscriptions = [
  {
    id: 1,
    formationId: 1,
    formationTitre: "React avancé & Performance",
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    dateInscription: "2026-07-01",
    statut: "confirmee",
  },
  {
    id: 2,
    formationId: 3,
    formationTitre: "Prise de parole en public",
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    dateInscription: "2026-07-05",
    statut: "en_attente",
  },
  {
    id: 3,
    formationId: 4,
    formationTitre: "Sécurité informatique & RGPD",
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    dateInscription: "2026-05-20",
    statut: "terminee",
  },
  {
    id: 4,
    formationId: 2,
    formationTitre: "Management d'équipe agile",
    employeNom: "Cheikh Kanté",
    employeEmail: "cheikh.kante@rh.com",
    dateInscription: "2026-07-08",
    statut: "en_attente",
  },
  {
    id: 5,
    formationId: 4,
    formationTitre: "Sécurité informatique & RGPD",
    employeNom: "Modou Seck",
    employeEmail: "modou.seck@rh.com",
    dateInscription: "2026-05-22",
    statut: "annulee",
  },
];
