export const typesEvenement = [
  "Promotion",
  "Mutation",
  "Changement de poste",
  "Augmentation salariale",
];

export const mockHistoriqueCarriere = [
  {
    id: 1,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    type: "Changement de poste",
    ancienPoste: "Développeuse Junior",
    nouveauPoste: "Développeuse Frontend",
    departement: "Technique",
    date: "2023-01-15",
    commentaire: "Montée en compétence sur React confirmée.",
  },
  {
    id: 2,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    type: "Augmentation salariale",
    ancienPoste: "Développeuse Frontend",
    nouveauPoste: "Développeuse Frontend",
    departement: "Technique",
    date: "2026-01-10",
    commentaire: "Revalorisation annuelle.",
  },
  {
    id: 3,
    employeNom: "Moussa Diop",
    employeEmail: "manager@rh.com",
    type: "Promotion",
    ancienPoste: "Développeur Senior",
    nouveauPoste: "Chef de projet",
    departement: "Technique",
    date: "2020-06-01",
    commentaire: "Prise de responsabilité de l'équipe technique.",
  },
  {
    id: 4,
    employeNom: "Cheikh Kanté",
    employeEmail: "cheikh.kante@rh.com",
    type: "Mutation",
    ancienPoste: "Développeur Backend",
    nouveauPoste: "Développeur Backend",
    departement: "Technique",
    date: "2024-03-01",
    commentaire: "Rattachement à l'équipe API centrale.",
  },
];

export const mockSouhaitsEvolution = [
  {
    id: 1,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    posteSouhaite: "Lead Développeuse Frontend",
    mobiliteGeographique: false,
    commentaire: "Souhaite évoluer vers un rôle d'encadrement technique.",
    dateSoumission: "2026-06-10",
    statut: "en_attente",
  },
  {
    id: 2,
    employeNom: "Cheikh Kanté",
    employeEmail: "cheikh.kante@rh.com",
    posteSouhaite: "Architecte Backend",
    mobiliteGeographique: true,
    commentaire: "Ouvert à une mobilité vers le bureau de Thiès.",
    dateSoumission: "2026-05-20",
    statut: "examine",
  },
  {
    id: 3,
    employeNom: "Modou Seck",
    employeEmail: "modou.seck@rh.com",
    posteSouhaite: "Développeur Fullstack Senior",
    mobiliteGeographique: false,
    commentaire: "",
    dateSoumission: "2026-04-02",
    statut: "planifie",
  },
];
