export const typesDocument = [
  "Bulletin de paie",
  "Contrat de travail",
  "Attestation de travail",
  "Attestation de salaire",
  "Autre",
];

export const mockDocuments = [
  {
    id: 1,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    type: "Bulletin de paie",
    titre: "Bulletin de paie — Juin 2026",
    dateAjout: "2026-07-01",
    fichierNom: "bulletin_juin_2026_awa_sarr.pdf",
  },
  {
    id: 2,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    type: "Bulletin de paie",
    titre: "Bulletin de paie — Mai 2026",
    dateAjout: "2026-06-01",
    fichierNom: "bulletin_mai_2026_awa_sarr.pdf",
  },
  {
    id: 3,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    type: "Contrat de travail",
    titre: "Contrat CDI",
    dateAjout: "2021-09-15",
    fichierNom: "contrat_cdi_awa_sarr.pdf",
  },
  {
    id: 4,
    employeNom: "Awa Sarr",
    employeEmail: "salarie@rh.com",
    type: "Attestation de travail",
    titre: "Attestation de travail 2026",
    dateAjout: "2026-06-20",
    fichierNom: "attestation_travail_awa_sarr.pdf",
  },
  {
    id: 5,
    employeNom: "Moussa Diop",
    employeEmail: "manager@rh.com",
    type: "Bulletin de paie",
    titre: "Bulletin de paie — Juin 2026",
    dateAjout: "2026-07-01",
    fichierNom: "bulletin_juin_2026_moussa_diop.pdf",
  },
  {
    id: 6,
    employeNom: "Moussa Diop",
    employeEmail: "manager@rh.com",
    type: "Contrat de travail",
    titre: "Contrat CDI",
    dateAjout: "2020-06-01",
    fichierNom: "contrat_cdi_moussa_diop.pdf",
  },
  {
    id: 7,
    employeNom: "Cheikh Kanté",
    employeEmail: "cheikh.kante@rh.com",
    type: "Attestation de salaire",
    titre: "Attestation de salaire 2026",
    dateAjout: "2026-05-10",
    fichierNom: "attestation_salaire_cheikh_kante.pdf",
  },
];
