export const departements = [
  "Ressources Humaines",
  "Technique",
  "Commercial",
  "Finance",
  "Marketing",
];

export const typesContrat = ["CDI", "CDD", "Stage", "Alternance"];

export const mockEmployes = [
  {
    id: 1,
    nom: "Fatou Ndiaye",
    email: "admin@rh.com",
    poste: "Responsable RH",
    departement: "Ressources Humaines",
    dateEmbauche: "2019-03-12",
    statut: "actif",
    role: "admin_rh",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 2,
    nom: "Moussa Diop",
    email: "manager@rh.com",
    poste: "Chef de projet",
    departement: "Technique",
    dateEmbauche: "2020-06-01",
    statut: "actif",
    role: "manager",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 3,
    nom: "Awa Sarr",
    email: "salarie@rh.com",
    poste: "Développeuse Frontend",
    departement: "Technique",
    dateEmbauche: "2021-09-15",
    statut: "actif",
    role: "salarie",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 4,
    nom: "Aminata Diouf",
    email: "aminata.diouf@rh.com",
    poste: "Commercial",
    departement: "Commercial",
    dateEmbauche: "2025-09-01",
    statut: "conge",
    role: "salarie",
    typeContrat: "CDD",
    dateFinContrat: "2026-08-31",
  },
  {
    id: 5,
    nom: "Aissatou Diallo",
    email: "aissatou.diallo@rh.com",
    poste: "Comptable",
    departement: "Finance",
    dateEmbauche: "2018-11-20",
    statut: "actif",
    role: "salarie",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 6,
    nom: "Cheikh Kanté",
    email: "cheikh.kante@rh.com",
    poste: "Développeur Backend",
    departement: "Technique",
    dateEmbauche: "2023-02-05",
    statut: "actif",
    role: "salarie",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 7,
    nom: "Mariama Sy",
    email: "mariama.sy@rh.com",
    poste: "Chargée de recrutement",
    departement: "Ressources Humaines",
    dateEmbauche: "2020-08-18",
    statut: "actif",
    role: "salarie",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 8,
    nom: "Ousmane Fall",
    email: "ousmane.fall@rh.com",
    poste: "Responsable Marketing",
    departement: "Marketing",
    dateEmbauche: "2019-07-22",
    statut: "inactif",
    role: "manager",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 9,
    nom: "Khady Gueye",
    email: "khady.gueye@rh.com",
    poste: "Analyste Financier",
    departement: "Finance",
    dateEmbauche: "2021-04-09",
    statut: "actif",
    role: "salarie",
    typeContrat: "CDI",
    dateFinContrat: null,
  },
  {
    id: 10,
    nom: "Modou Seck",
    email: "modou.seck@rh.com",
    poste: "Développeur Fullstack",
    departement: "Technique",
    dateEmbauche: "2026-04-01",
    statut: "conge",
    role: "salarie",
    typeContrat: "Stage",
    dateFinContrat: "2026-07-25",
  },
];
