export const mockOffres = [
  {
    id: 1,
    titre: "Développeur Fullstack React/Laravel",
    departement: "Technique",
    type: "CDI",
    localisation: "Dakar",
    statut: "ouverte",
    datePublication: "2026-06-01",
  },
  {
    id: 2,
    titre: "Chargé de recrutement",
    departement: "Ressources Humaines",
    type: "CDI",
    localisation: "Dakar",
    statut: "ouverte",
    datePublication: "2026-06-15",
  },
  {
    id: 3,
    titre: "Analyste Financier",
    departement: "Finance",
    type: "CDD",
    localisation: "Dakar",
    statut: "fermee",
    datePublication: "2026-04-10",
  },
  {
    id: 4,
    titre: "Stagiaire Marketing Digital",
    departement: "Marketing",
    type: "Stage",
    localisation: "Dakar",
    statut: "ouverte",
    datePublication: "2026-07-01",
  },
];

export const mockCandidatures = [
  {
    id: 1,
    offreId: 1,
    offreTitre: "Développeur Fullstack React/Laravel",
    candidatNom: "Ibrahima Ba",
    candidatEmail: "candidat@rh.com",
    dateCandidature: "2026-06-20",
    statut: "en_entretien",
    cvNom: "CV_Ibrahima_Ba.pdf",
    lettreNom: "Lettre_motivation_Ibrahima_Ba.pdf",
  },
  {
    id: 2,
    offreId: 1,
    offreTitre: "Développeur Fullstack React/Laravel",
    candidatNom: "Ibrahima Ba",
    candidatEmail: "candidat@rh.com",
    dateCandidature: "2026-06-05",
    statut: "recue",
    cvNom: "CV_Ibrahima_Ba.pdf",
    lettreNom: "Lettre_motivation_Ibrahima_Ba.pdf",
  },
  {
    id: 3,
    offreId: 2,
    offreTitre: "Chargé de recrutement",
    candidatNom: "Ibrahima Ba",
    candidatEmail: "candidat@rh.com",
    dateCandidature: "2026-06-18",
    statut: "acceptee",
    cvNom: "CV_Ibrahima_Ba.pdf",
    lettreNom: "Lettre_motivation_Ibrahima_Ba.pdf",
  },
  {
    id: 4,
    offreId: 3,
    offreTitre: "Analyste Financier",
    candidatNom: "Ibrahima Ba",
    candidatEmail: "candidat@rh.com",
    dateCandidature: "2026-04-15",
    statut: "refusee",
    cvNom: "CV_Ibrahima_Ba.pdf",
    lettreNom: "Lettre_motivation_Ibrahima_Ba.pdf",
  },
];
